Mostly zero change cleanups and stylings
christerk/FFBUnity pull request #47
Opened 2019-12-13 21:37 UTC by SzieberthAdam

2019-12-13 22:02 UTC, SzieberthAdam commented
Mostly zero change code uniformization and cleanups. I looked over the whole codebase multiple times for this. I really think that readability got better and the code look nicer after these changes. Tested with the Unity Editor.

Exceptions (minor real changes):
- 1280706: added a using of Model.Types
- abde896: Pass Block color uses settings

2019-12-13 22:17 UTC, christerk requested changes
This is a way too big PR. If you're doing this type of style cleanup, do separate PRs for each type of change to keep things small.

Also, do not have actual code changes in a PR like this as it becomes impossible to track those when looking back at commit history.

2019-12-13 22:17 UTC, christerk commented on Assets/ActionInjectorHandler.cs
> +    //  MONOBEHAVIOUR METHODS  ////////////////////////////////////////////////
No, this is not how to do this.

If you're doing grouping of code like this, use `#region`

2019-12-13 22:17 UTC, christerk commented on Assets/ActionInjectorHandler.cs
> +    //  CUSTOM METHODS  ///////////////////////////////////////////////////////
`#region`

2019-12-13 22:17 UTC, christerk commented on Assets/BlockDiceHandler.cs
> +    private static Vector2 SmallSize = new Vector2(30, 30);
If you are going to organize fields and properties, public before private is the way to go.

2019-12-13 22:17 UTC, christerk commented on Assets/BlockDiceHandler.cs
> +    //  MONOBEHAVIOUR METHODS  ////////////////////////////////////////////////
`#region`. Not adding further comments about this particular style.

2019-12-13 22:17 UTC, christerk commented on Assets/FieldHandler.cs
> +    private GameObject Ball;
public before private

2019-12-13 22:17 UTC, christerk commented on Assets/FieldHandler.cs
> +    private void OnDestroy()
I want life cycle methods grouped together. Start() followed by OnDestroy() to make it easier to follow when you read the code.

2019-12-13 22:17 UTC, christerk commented on Assets/Scripts/Ffb/Dto/ModelChanges/FieldModelAddPushbackSquare.cs
> +        public FieldModelAddPushbackSquare() : base("fieldModelAddPushbackSquare")
This is unnecessary. The constructor calls the base class constructor and doesn't do anything and won't ever do anything beyond that. Leave it as it was.

2019-12-13 22:17 UTC, christerk commented on Assets/Scripts/Model/Types/Player.cs
> +        public Player()
As a general rule, fields and properties before constructor. I know the DTOs have the constructor first and if you insist on unifying this, it's better to change the DTOs to match the more general case.

2019-12-13 22:17 UTC, christerk commented on Assets/SettingsHandler.cs
> +    public void UpdateAbstractIcons()
public before private if you're reorganizing methods.

2019-12-13 22:17 UTC, christerk commented on Assets/GameBrowserEntry.cs
> +    //  CUSTOM METHODS  ///////////////////////////////////////////////////////
Don't need to state something as generic as "custom methods". Use `#region` to group monobehaviour and leave these outside that region.

2019-12-13 22:22 UTC, SzieberthAdam commented
I give further comments to the individual commits to help reviewing:
- 7adbd14: Zero change. Methods sorted alphabetically.
- 483f9b1: Zero change. Only removed trailing ` {}`s. 
- 593ca1b: Zero change. Added an empty line.
- bc4bf88: **Minor change**: Coach color uses settings.
- 946dd92: **Minor change**: Gender Nominative field got to private to match other fields.
- 6e63d63: Zero change. Fields ordered alphabetically.
- 99dc591: Zero change. I expected MonoBehaviour subclasses' got their methods and fields just throwed in. Made some order and visually separated the custom and the mono methods.
- 7c87d5c: **Minor change**: Some access modes were explicit some were excluded. I made all of them explicit here.
- 360dc4f **Minor change**: The code were full of unnecessary using directives. I removed them where the IDE indicated it.
- e607c5c: Zero change. The ModelChange class constructors had their curly brackets put differently. Some were at the end like ` {}` and some were put into the subsequent two lines. I made all to the latter style.
- b7b45ed **Minor change**. Using directives again. Missed to click to stage them when I commited 360dc4f,
- fc382ea Zero change: Add and remove empty lines.
- 1280706 **Minor change**: added a using of Model.Types and chenged the qualified name of Coordinates
- 0cdd824 Zero change. Moved the constructor up to match other modules approach.
- b36def2 Zero change. Ordered the fields.
- abde896 **Minor change**: Pass Block Log text uses settings color
- ae35902 Zero change: Various. Missed to save them in the editor in the first place.

2019-12-14 01:31 UTC, SzieberthAdam commented
Number of changed files has been grown as I moved the constructors of the DTOs after the fields.

2019-12-14 10:10 UTC, christerk commented
Resolve the conflict please.

2019-12-14 10:45 UTC, SzieberthAdam commented
Resolved. LiginHandler.Login() got public in the meantime to be able to get called by the login scene button.

2019-12-14 16:32 UTC, merged