Implemented Log Texts / Server commands
christerk/FFBUnity pull request #61
Opened 2019-12-20 15:30 UTC by stowelly

several simple Log Texts implemented. also serverAddPlayer implemented

2019-12-20 17:47 UTC, christerk requested changes
Some changes needed as outlined in comments.

2019-12-20 17:47 UTC, christerk commented on Assets/ConnectionHandler.cs
> +                foreach( var pos in FFB.Instance.Model.PositionsHome)
Odd spacing after foreach

2019-12-20 17:47 UTC, christerk commented on Assets/ConnectionHandler.cs
> +                foreach( var pos in FFB.Instance.Model.PositionsAway)
Again, same odd spacing.

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/Commands/ServerAddPlayer.cs
> +            Player player = new Player()
This is making me uneasy. It's a second place with the same partial code..

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/Ffb/Dto/Commands/ServerAddPlayer.cs
> +      //  public PlayerState playerState;
Decide if you want this here or not; either uncomment or remove the line.

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/Lib/Cache.cs
> +            if(key != null && cache.TryGetValue(key, out cacheObject))
No need to construct the object if key is null. Possibly also investigate if `new CacheObject()` needs to be called here at all.

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/UI/LogText/PilingOn.cs
> +            string armourOrInjury = report.used? report.reRollInjury ? " to re-roll Injury" : " to re-roll Armour" : "";
This is super confusing (and missing a space). Improve code clarity.

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/UI/LogText/Spectators.cs
> +            string rollString = "[ ";
Change this to something like:
`return $"[ {string.Join(" ][ ", rolls)} ]";`

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/UI/LogText/Spectators.cs
> +            return string.Join(",", rolls) + " Fan Factor = " + rolls.Sum();
Similar to previous comment, change this to a `$"...."` construct.

2019-12-20 17:47 UTC, christerk commented on Assets/Scripts/UI/LogText/Weather.cs
> +        private string WeatherRollString(int[] rolls)
This is the exact same method as earlier in this PR. Refactor this into shared code; can be placed in the LogTextGenerator superclass, or possibly in some utility static class.

2019-12-21 09:34 UTC, stowelly commented
Changes actioned!

2019-12-21 11:07 UTC, christerk requested changes

2019-12-21 11:07 UTC, christerk commented on Assets/Scripts/Commands/ServerGameState.cs
> +                FFB.Instance.Model.PositionsHome[pos.positionId] = new Position()
If this is pushed into the model, get rid of the separate structures for home and away positions and unify them into a single one. The only reason it's separated here is to do a very crude consistency check, but that isn't necessary to push into the model.

Also, don't use an indexer into an external class like this, make a `Model.Add(Position pos)` method for this purpose. Similarly, make a `Model.GetPosition(string positionId)` which is how players work.

2019-12-21 11:07 UTC, christerk commented on Assets/Scripts/Commands/ServerAddPlayer.cs
> +            Player player = new Player(p, t, position);
Is it worth the effort to maintain separation between the model and the DTOs by moving this into its own factory class rather than having it in the model? Having the link between the model and the DTOs separate is clean from the model's perspective, but creates another level if indirection. The reason I didn't have this code in the Player class in the first place is in case we wanted to extract the model for other purposes at a later stage and generally keep the model self-contained.

I'm not sure, either way is fine but there needs to be a conscious decision made about this.

2019-12-21 11:07 UTC, christerk commented on Assets/Scripts/Commands/ServerGameState.cs
> +               FFB.Instance.Model.PositionsAway[pos.positionId] = new Position()
This should use the same method of constructing position instances as the players above.

2019-12-21 13:06 UTC, christerk commented on Assets/Scripts/Model/Core.cs
> +        internal void AddPosition(string id, Position position)
This should not have a `string id` parameter. Like the player, this id should be fetched from the position object.

2019-12-21 14:51 UTC, merged